<script setup lang="ts">
import{computed,ref,watch}from'vue';import{useRoute}from'vue-router';import CompanyCard from'../components/CompanyCard.vue';import FilterGuide from'../components/FilterGuide.vue';import{companies,state}from'../stores/career';import{fitScore,visaFit}from'../services/recommendations';import{csv,download}from'../services/export';
const route=useRoute();const q=ref(''),city=ref(String(route.query.city||'')),industry=ref(''),priority=ref(String(route.query.priority||'')),visa=ref(''),status=ref(''),page=ref(1),pageSize=ref(12);
const cities=[...new Set(companies.flatMap(x=>x.cities))].sort(),industries=[...new Set(companies.map(x=>x.industry))].sort();
const list=computed(()=>companies.filter(x=>(!q.value||JSON.stringify(x).toLowerCase().includes(q.value.toLowerCase()))&&(!city.value||x.cities.includes(city.value))&&(!industry.value||x.industry===industry.value)&&(!priority.value||x.priority===priority.value)&&(!visa.value||visaFit(x)[0]===visa.value)&&(!status.value||(state.statuses[x.name]||'未开始')===status.value)).sort((a,b)=>fitScore(b)-fitScore(a)||a.name.localeCompare(b.name)));
const pageCount=computed(()=>Math.max(1,Math.ceil(list.value.length/pageSize.value)));const visible=computed(()=>list.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value));const pages=computed(()=>Array.from({length:pageCount.value},(_,i)=>i+1));
watch([q,city,industry,priority,visa,status,pageSize],()=>page.value=1);watch(pageCount,n=>{if(page.value>n)page.value=n});
function weekly(){city.value='Melbourne';priority.value='P1';visa.value='主申请池';status.value='未开始'}function reset(){q.value=city.value=industry.value=priority.value=visa.value=status.value=''}
function exportList(){download(csv([['公司','城市','行业','岗位','原因','签证适配','优先级','状态','链接'],...list.value.map(x=>[x.name,x.cities.join('|'),x.industry,x.recommendedRoles.join('|'),x.fitReason,visaFit(x)[0],x.priority,state.statuses[x.name]||'未开始',x.careerUrl])]),'career-companies.csv','text/csv')}
function go(n:number){page.value=Math.max(1,Math.min(pageCount.value,n));document.querySelector('.results-head')?.scrollIntoView({behavior:'smooth',block:'start'})}
</script>
<template><main><div class="section-head"><div><div class="eyebrow">ALL TARGETS</div><h1>公司目录</h1></div><div><span>{{list.length}} / {{companies.length}} 家</span> <button class="button" @click="exportList">导出筛选结果</button></div></div><FilterGuide/><div class="actions"><button class="button primary" @click="weekly">只看本周主攻</button><button class="button" @click="reset">重置筛选</button></div><div class="filters card"><label><span>1. 关键词</span><input v-model="q" placeholder="公司、岗位或方向"></label><label><span>2. 城市</span><select v-model="city"><option value="">全部城市</option><option v-for="x in cities">{{x}}</option></select></label><label><span>3. 行业</span><select v-model="industry"><option value="">全部行业</option><option v-for="x in industries">{{x}}</option></select></label><label><span>4. 优先级</span><select v-model="priority"><option value="">P1 + P2 + P3</option><option>P1</option><option>P2</option><option>P3</option></select></label><label><span>5. 签证适配</span><select v-model="visa"><option value="">全部适配度</option><option>主申请池</option><option>逐条核对</option><option>通常受限</option></select></label><label><span>6. 申请状态</span><select v-model="status"><option value="">全部状态</option><option>未开始</option><option>研究中</option><option>已投递</option><option>面试中</option><option>暂停</option></select></label></div><div class="results-head"><p>按匹配分从高到低排列 · 第 {{page}} / {{pageCount}} 页</p><label>每页 <select v-model.number="pageSize"><option :value="6">6</option><option :value="12">12</option><option :value="24">24</option></select> 家</label></div><div class="company-grid"><CompanyCard v-for="c in visible" :key="c.id" :company="c"/></div><p v-if="!visible.length" class="card empty">没有符合这些条件的公司。可以减少一个筛选条件再试。</p><nav v-if="pageCount>1" class="pagination" aria-label="公司结果分页"><button class="page-button" :disabled="page===1" @click="go(page-1)">上一页</button><button v-for="n in pages" :key="n" class="page-button" :class="{active:n===page}" :aria-current="n===page?'page':undefined" @click="go(n)">{{n}}</button><button class="page-button" :disabled="page===pageCount" @click="go(page+1)">下一页</button></nav></main></template>
