<script setup lang="ts">
import { computed,reactive } from 'vue';
import jobs from '../data/daily-jobs.json';
import { strategy } from '../stores/strategy';
import { matchJob } from '../services/jobMatching';
const feedback=reactive<Record<string,string>>(JSON.parse(localStorage.getItem('career-os-match-feedback')||'{}'));
const matches=computed(()=>jobs.map(job=>matchJob(job,strategy)).sort((a,b)=>b.score-a.score));
function react(id:string,value:string){feedback[id]=value;localStorage.setItem('career-os-match-feedback',JSON.stringify(feedback));}
</script>
<template><main class="match-page"><div class="match-header"><div><div class="eyebrow">EXPLAINABLE JOB MATCHING</div><h1>职位匹配</h1><p class="lede">只有准确官方职位页面、职位名称和地点一起核验后，才进入匹配。先检查资格，再比较简历证据、职级、方向与城市。</p></div><RouterLink to="/strategy" class="button primary">修改我的策略</RouterLink></div>
<div class="match-summary"><span>P1 {{matches.filter(x=>x.priority==='P1').length}}</span><span>P2 {{matches.filter(x=>x.priority==='P2').length}}</span><span>P3 {{matches.filter(x=>x.priority==='P3').length}}</span><span>策略城市：{{strategy.cities.join(' / ')||'未设置'}}</span></div>
<section class="match-list"><article v-for="m in matches" :key="m.job.id" class="card match-card"><div class="match-score" :data-priority="m.priority"><strong>{{m.priority}}</strong><span>{{m.score}} / 100</span><small>置信度 {{m.confidence}}</small></div><div class="match-content"><div class="match-title"><div><h2>{{m.job.role}}</h2><p>{{m.job.company}} · {{m.job.location}}</p></div><span class="pill">{{m.eligibility}}</span></div><p><b>{{m.reason}}</b></p><div class="evidence-grid"><section><h3>为什么匹配</h3><ul><li v-for="item in m.evidence" :key="item">{{item}}</li><li v-if="!m.evidence.length">没有足够的直接证据。</li></ul></section><section><h3>缺口与风险</h3><ul><li v-for="item in m.gaps" :key="item">{{item}}</li></ul></section></div><p class="verification-note"><b>页面核验：</b>{{m.job.verificationNote}}（{{m.job.verifiedAt}}）</p><p class="meta">截止：{{m.job.deadline}} · 点击后应进入同一职位的官方详情页；若发生重定向，请不要申请并反馈失效。</p><div class="actions"><a :href="m.job.url" target="_blank" rel="noopener noreferrer" class="button primary">打开准确官方职位 ↗</a><RouterLink :to="{path:'/tracker',query:{company:m.job.company,role:m.job.role,jobUrl:m.job.url}}" class="button">加入追踪</RouterLink></div><div class="match-feedback"><span>这个推荐准确吗？</span><button :class="{selected:feedback[m.job.id]==='yes'}" @click="react(m.job.id,'yes')">准确</button><button :class="{selected:feedback[m.job.id]==='senior'}" @click="react(m.job.id,'senior')">太Senior</button><button :class="{selected:feedback[m.job.id]==='direction'}" @click="react(m.job.id,'direction')">方向不喜欢</button></div></div></article></section></main></template>
