<script setup lang="ts">
import { profile, profileMessage, safeLink } from '../stores/profile';
import { download } from '../services/export';
const fields=[['name','称呼'],['city','所在地'],['education','教育背景'],['strengths','优势与经验'],['goal','职业目标'],['visa','签证与工作权说明'],['linkedin','LinkedIn URL'],['seek','SEEK URL'],['portfolio','作品集 URL']] as const;
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.type!=='application/pdf'||file.size>2*1024*1024){profileMessage.text='请选择不超过 2 MB 的 PDF 简历。';return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});profile.resumeName=file.name;profile.resumeData=data;}catch{profileMessage.text='简历读取失败，请重试。';}}
function resume(){if(!profile.resumeData.startsWith('data:application/pdf;base64,'))return;const a=document.createElement('a');a.href=profile.resumeData;a.download=profile.resumeName||'resume.pdf';a.click();}
async function restore(event:Event){try{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>4*1024*1024)throw Error();const data=JSON.parse(await file.text());if(data.kind!=='career-os-profile'||!data.profile)throw Error();for(const key of Object.keys(profile) as (keyof typeof profile)[])if(typeof data.profile[key]==='string')profile[key]=data.profile[key];profileMessage.text='资料已恢复';}catch{profileMessage.text='备份格式无效，未能恢复。';}}
</script>
<template><main class="workspace"><div class="eyebrow">MY CAREER IDENTITY</div><h1>个人档案</h1><p class="lede">我是谁、可以带来什么、申请材料在哪里——集中在一个地方。</p>
<section class="card panel"><h2>{{profile.name||'你的职业名片'}}</h2><p>{{profile.education}} · {{profile.city}}</p><p>{{profile.strengths}}</p><p>目标：{{profile.goal}}</p><p class="meta">画像为可编辑自述；目前公司评分仍使用原有 Melbourne 画像规则，不会因为修改档案而自动重算。</p></section>
<form class="profile-form card panel" @submit.prevent><label v-for="[key,label] in fields" :key="key">{{label}}<input v-model="profile[key]" :type="['linkedin','seek','portfolio'].includes(key)?'url':'text'" :placeholder="key==='name'?'填写你的称呼':''"></label></form>
<section class="card panel"><h2>简历与外部档案</h2><div class="actions"><label class="button">保存 / 替换 PDF 简历<input hidden type="file" accept="application/pdf" @change="upload"></label><button v-if="profile.resumeData" class="button" @click="resume">下载 {{profile.resumeName}}</button><a v-for="key in (['linkedin','seek','portfolio'] as const)" :key="key" v-show="safeLink(profile[key])" :href="safeLink(profile[key])" target="_blank" rel="noopener noreferrer" class="button">{{key}}</a></div><p class="meta">最多 2 MB PDF。仅保存于当前浏览器；清理浏览器数据会丢失。外部链接不会同步账号、读取职位或代你投递。</p><p role="status">{{profileMessage.text}}</p><button class="button" @click="download(JSON.stringify({kind:'career-os-profile',profile}),'career-os-profile.json','application/json')">备份个人资料与简历</button> <label class="button">恢复个人备份<input hidden type="file" accept="application/json" @change="restore"></label><p class="meta">此备份含个人资料，请妥善保管。原投递追踪备份功能保持不变。</p></section></main></template>
