<script setup lang="ts">
import { reactive,ref,computed } from 'vue';
import { useRoute } from 'vue-router';
import { addApplication,updateApplication,deleteApplication,state } from '../stores/career';
import { backup,saveApplications,saveStatuses } from '../services/storage';
import { profile,safeLink } from '../stores/profile';
import { csv,download } from '../services/export';
import type { Application } from '../types';
const route=useRoute(),editing=ref<number|null>(null),message=ref(''),view=ref<'list'|'board'>('list');
const empty=()=>({company:'',role:'',city:'Melbourne',status:'研究中',date:'',note:'',jobUrl:'',deadline:'',nextDate:'',nextAction:'',resumeVersion:'BA / Digital Delivery',eligibility:'待核实'});
const form=reactive({...empty(),company:String(route.query.company||''),role:String(route.query.role||''),jobUrl:String(route.query.jobUrl||''),deadline:String(route.query.deadline||'')});
const fields=[['company','公司','text'],['role','真实职位','text'],['city','城市','text'],['jobUrl','官方职位链接','url'],['date','提交日期','date'],['deadline','截止日期','date'],['nextDate','下一步日期','date'],['nextAction','下一步行动','text'],['resumeVersion','简历版本','text']] as const;
const statuses=['研究中','已投递','面试中','Offer','拒绝','暂停','撤回'];
const duplicate=computed(()=>state.applications.some(a=>a.id!==editing.value&&a.company.trim().toLowerCase()===form.company.trim().toLowerCase()&&a.role.trim().toLowerCase()===form.role.trim().toLowerCase()));
const due=computed(()=>state.applications.filter(a=>a.nextDate&&a.nextDate<=new Date().toLocaleDateString('en-CA',{timeZone:'Australia/Sydney'})&&!['Offer','拒绝','撤回','暂停'].includes(a.status)));
const boardStatuses=['研究中','已投递','面试中','Offer','拒绝'] as const;
const byStatus=(status:string)=>state.applications.filter(a=>a.status===status);
function move(a:Application,status:string){const{id,...value}=a;updateApplication(id,{...value,status});message.value=`${a.company} 已更新为${status}`;}
function cancel(){editing.value=null;Object.assign(form,empty());}
function edit(a:Application){editing.value=a.id;Object.assign(form,empty(),a);window.scrollTo({top:0,behavior:'smooth'});}
function submit(){if(form.jobUrl&&!safeLink(form.jobUrl)){message.value='链接必须使用 HTTP 或 HTTPS';return;}if(duplicate.value&&!confirm('已有同公司、同职位记录，仍要保存吗？'))return;try{if(editing.value!==null)updateApplication(editing.value,{...form});else addApplication({...form});cancel();message.value='申请记录已保存';}catch{message.value='浏览器保存失败，请立即备份。';}}
function remove(id:number){if(confirm('删除这条申请记录？请先备份，删除后无法直接撤销。'))deleteApplication(id);}
function backupAll(){const d=JSON.parse(backup(state.statuses,state.applications));download(JSON.stringify({...d,version:3,profile,checklist:JSON.parse(localStorage.getItem('career-os-checklist')||'{}')}),'career-os-backup.json','application/json');}
function exportAll(){download(csv([['公司','职位','城市','状态','提交日期','备注','职位链接','截止日','下一步日期','下一步','简历版本','资格'],...state.applications.map(a=>[a.company,a.role,a.city,a.status,a.date,a.note,a.jobUrl,a.deadline,a.nextDate,a.nextAction,a.resumeVersion,a.eligibility])]),'application-tracker.csv','text/csv');}
async function restore(event:Event){try{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>8*1024*1024)throw Error('文件过大');const d=JSON.parse(await file.text());if(!d.companyStatus||typeof d.companyStatus!=='object'||Array.isArray(d.companyStatus)||!Array.isArray(d.tracker)||!d.tracker.every((a:Application)=>typeof a.id==='number'&&['company','role','city','status','date','note'].every(k=>typeof (a as unknown as Record<string,unknown>)[k]==='string')))throw Error('无效备份');if(!confirm('恢复将覆盖现有投递记录和备份内的个人资料。是否继续？'))return;state.statuses=d.companyStatus;state.applications=d.tracker;saveStatuses(state.statuses);saveApplications(state.applications);if(d.profile)for(const key of Object.keys(profile) as (keyof typeof profile)[])if(typeof d.profile[key]==='string')profile[key]=d.profile[key];if(d.checklist){localStorage.setItem('career-os-checklist',JSON.stringify(d.checklist));}message.value='恢复完成；如恢复了清单，请刷新页面。';}catch{message.value='恢复失败：请检查备份格式或浏览器空间。';}}
</script>
<template><main class="workspace"><div class="section-head"><div><div class="eyebrow">APPLICATION PIPELINE</div><h1>投递追踪</h1></div><div class="actions"><button class="button" @click="backupAll">完整备份 JSON</button><label class="button">恢复备份<input hidden type="file" accept="application/json" @change="restore"></label><button class="button" @click="exportAll">导出 CSV</button></div></div>
<p class="meta">完整备份含档案、简历、清单、公司状态和申请记录，请妥善保管。兼容旧投递备份。记录状态不等于系统已代你提交。</p>
<div class="tracker-view-switch" role="group" aria-label="切换投递视图"><button type="button" :class="{active:view==='list'}" @click="view='list'">列表</button><button type="button" :class="{active:view==='board'}" @click="view='board'">看板</button></div>
<section v-if="due.length" class="card panel"><h2>到期行动 · {{due.length}}</h2><p v-for="a in due" :key="a.id">{{a.company}} · {{a.nextAction||'检查申请'}} · {{a.nextDate}} <button class="button" @click="edit(a)">更新</button></p></section>
<h2>{{editing!==null?'编辑申请':'新增真实职位'}}</h2><form class="profile-form card panel" @submit.prevent="submit"><label v-for="[key,label,type] in fields" :key="key">{{label}}<input v-model="form[key]" :type="type" :required="key==='company'||key==='role'"></label><label>状态<select v-model="form.status"><option v-for="s in statuses" :key="s">{{s}}</option></select></label><label>资格核验<select v-model="form.eligibility"><option>待核实</option><option>符合（自行核验）</option><option>明确不符合</option></select></label><label>证据、缺口与备注<textarea v-model="form.note" placeholder="广告要求 → 对应经历 → 尚缺证据"></textarea></label><div><p v-if="duplicate" class="meta">可能重复：同公司、同职位已存在。</p><button class="button primary">{{editing!==null?'保存修改':'加入追踪'}}</button> <button type="button" class="button" @click="cancel">取消 / 清空</button></div></form><p role="status">{{message}}</p>
<div v-if="view==='list'" class="stack"><article v-for="a in state.applications" :key="a.id" class="card panel"><div class="section-head"><h2>{{a.company}} · {{a.role}}</h2><span class="pill">{{a.status}}</span></div><p>{{a.city}} · {{a.eligibility||'待核实'}} · 简历：{{a.resumeVersion||'未记录'}}</p><p class="meta">提交：{{a.date||'未记录'}} · 截止：{{a.deadline||'未记录'}} · 下一步日期：{{a.nextDate||'未记录'}}</p><p>{{a.nextAction||'请设置下一步行动'}}</p><p>{{a.note}}</p><div class="actions"><a v-if="safeLink(a.jobUrl||'')" :href="safeLink(a.jobUrl||'')" target="_blank" rel="noopener noreferrer" class="button">打开职位</a><button class="button" @click="edit(a)">编辑 / 更新状态</button><button class="button" @click="remove(a.id)">删除</button></div></article></div>
<div v-else class="application-board"><section v-for="status in boardStatuses" :key="status" class="board-column"><header><b>{{status}}</b><span>{{byStatus(status).length}}</span></header><article v-for="a in byStatus(status)" :key="a.id" class="board-card"><b>{{a.company}}</b><p>{{a.role}}</p><small>{{a.nextDate?`下一步 ${a.nextDate}`:'未设下一步'}}</small><select :value="a.status" aria-label="更新申请状态" @change="move(a,($event.target as HTMLSelectElement).value)"><option v-for="s in statuses" :key="s">{{s}}</option></select><button class="button" @click="edit(a)">详情</button></article><p v-if="!byStatus(status).length" class="board-empty">暂无记录</p></section></div>
<p v-if="!state.applications.length" class="card empty">没有真实职位记录。先核验广告，再加入追踪。</p></main></template>
